[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Ccode-model=medium",
    "-Crelocation-model=static",
    "-Clink-arg=-Tkernel/src/arch/riscv64/kernel.ld",
]

[target.x86_64-unknown-none]
rustflags = [
    "-Crelocation-model=static",
    "-Ccode-model=small",
    "-Cno-redzone=yes",
    "-Clink-arg=-Tkernel/src/arch/x86_64/kernel.ld",
]
